/**
 * @license
 * Copyright 2025 Ollama Code Team
 * SPDX-License-Identifier: Apache-2.0
 */

import * as fs from 'fs';
import * as path from 'path';
import { CompressionStatus, type ChatCompressionInfo } from '../core/turn.js';
import { createDebugLogger } from '../utils/debugLogger.js';
import type { Config } from '../config/config.js';

const debugLogger = createDebugLogger('COMPRESSION_REPORT');

/**
 * Compression report data structure
 */
export interface CompressionReport {
  timestamp: string;
  sessionId: string;
  status: CompressionStatus;
  originalTokenCount: number;
  newTokenCount: number;
  savedTokens: number;
  savedPercent: number;
  duration: number;
  summary?: string;
}

/**
 * Service for generating compression reports.
 * Stores reports in project directory.
 */
export class CompressionReportService {
  private reportsDir: string;
  private sessionId: string;

  constructor(appConfig: Config, sessionId?: string) {
    this.sessionId = sessionId || appConfig.getSessionId();
    this.reportsDir = path.join(
      appConfig.getProjectRoot(),
      '.ollama-code',
      'compression-reports',
    );
  }

  /**
   * Generate a compression report after compression completes
   */
  async generateReport(
    info: ChatCompressionInfo,
    duration?: number,
  ): Promise<string | null> {
    try {
      const actualDuration = duration ?? info.duration ?? 0;
      const report: CompressionReport = {
        timestamp: new Date().toISOString(),
        sessionId: this.sessionId,
        status: info.compressionStatus,
        originalTokenCount: info.originalTokenCount,
        newTokenCount: info.newTokenCount,
        savedTokens: info.originalTokenCount - info.newTokenCount,
        savedPercent:
          info.originalTokenCount > 0
            ? Math.round(
                ((info.originalTokenCount - info.newTokenCount) /
                  info.originalTokenCount) *
                  100,
              )
            : 0,
        duration: actualDuration,
        summary: info.summary,
      };

      // Ensure reports directory exists
      if (!fs.existsSync(this.reportsDir)) {
        fs.mkdirSync(this.reportsDir, { recursive: true });
      }

      // Generate markdown report
      const reportPath = await this.saveMarkdownReport(report);

      debugLogger.info('Compression report generated', {
        path: reportPath,
        status: info.compressionStatus,
      });

      return reportPath;
    } catch (error) {
      debugLogger.error('Failed to generate compression report', error);
      return null;
    }
  }

  /**
   * Save report as markdown file
   */
  private async saveMarkdownReport(report: CompressionReport): Promise<string> {
    const filename = `compression-${report.timestamp.replace(/[:.]/g, '-')}.md`;
    const filepath = path.join(this.reportsDir, filename);

    const statusEmoji = this.getStatusEmoji(report.status);
    const statusText = this.getStatusText(report.status);

    const markdown = `# Compression Report

## Overview

| Property | Value |
|----------|-------|
| **Timestamp** | ${report.timestamp} |
| **Session ID** | ${report.sessionId.substring(0, 8)}... |
| **Status** | ${statusEmoji} ${statusText} |
| **Duration** | ${report.duration}ms |

## Token Statistics

| Metric | Value |
|--------|-------|
| **Original Tokens** | ${report.originalTokenCount.toLocaleString()} |
| **New Tokens** | ${report.newTokenCount.toLocaleString()} |
| **Tokens Saved** | ${report.savedTokens.toLocaleString()} |
| **Compression Rate** | ${report.savedPercent}% |

## Status Details

\`\`\`
${this.getStatusDescription(report.status)}
\`\`\`

${report.summary ? `## Summary\n\n\`\`\`\n${report.summary}\n\`\`\`\n` : ''}
---
*Generated by Ollama Code Compression Service*
`;

    fs.writeFileSync(filepath, markdown, 'utf-8');
    return filepath;
  }

  /**
   * Get emoji for compression status
   */
  private getStatusEmoji(status: CompressionStatus): string {
    switch (status) {
      case CompressionStatus.COMPRESSED:
        return '✅';
      case CompressionStatus.NOOP:
        return '⚪';
      case CompressionStatus.COMPRESSION_FAILED_INFLATED_TOKEN_COUNT:
        return '⚠️';
      case CompressionStatus.COMPRESSION_FAILED_EMPTY_SUMMARY:
        return '❌';
      case CompressionStatus.COMPRESSION_FAILED_TOKEN_COUNT_ERROR:
        return '❌';
      default:
        return '❓';
    }
  }

  /**
   * Get human-readable status text
   */
  private getStatusText(status: CompressionStatus): string {
    switch (status) {
      case CompressionStatus.COMPRESSED:
        return 'Compressed Successfully';
      case CompressionStatus.NOOP:
        return 'No Operation Needed';
      case CompressionStatus.COMPRESSION_FAILED_INFLATED_TOKEN_COUNT:
        return 'Failed: Token Inflation';
      case CompressionStatus.COMPRESSION_FAILED_EMPTY_SUMMARY:
        return 'Failed: Empty Summary';
      case CompressionStatus.COMPRESSION_FAILED_TOKEN_COUNT_ERROR:
        return 'Failed: Token Count Error';
      default:
        return 'Unknown Status';
    }
  }

  /**
   * Get detailed status description
   */
  private getStatusDescription(status: CompressionStatus): string {
    switch (status) {
      case CompressionStatus.COMPRESSED:
        return 'Compression completed successfully. The chat history has been summarized and token count reduced.';
      case CompressionStatus.NOOP:
        return 'No compression was needed. The context is already within optimal limits.';
      case CompressionStatus.COMPRESSION_FAILED_INFLATED_TOKEN_COUNT:
        return 'Compression was aborted because the resulting summary would have more tokens than the original history.';
      case CompressionStatus.COMPRESSION_FAILED_EMPTY_SUMMARY:
        return 'Compression failed because the model returned an empty or null summary.';
      case CompressionStatus.COMPRESSION_FAILED_TOKEN_COUNT_ERROR:
        return 'Compression failed because token counting encountered an error.';
      default:
        return 'Unknown compression status.';
    }
  }

  /**
   * List all compression reports
   */
  listReports(): string[] {
    if (!fs.existsSync(this.reportsDir)) {
      return [];
    }
    return fs
      .readdirSync(this.reportsDir)
      .filter((f) => f.endsWith('.md'))
      .sort()
      .reverse();
  }

  /**
   * Get the latest report path
   */
  getLatestReport(): string | null {
    const reports = this.listReports();
    if (reports.length === 0) {
      return null;
    }
    return path.join(this.reportsDir, reports[0]);
  }
}
