/**
 * @license
 * Copyright 2025 Ollama Code Team
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Unit tests for OllamaNativeClient.
 * These tests mock HTTP responses and don't require a running Ollama server.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  OllamaNativeClient,
  createOllamaNativeClient,
  DEFAULT_OLLAMA_NATIVE_URL,
} from './ollamaNativeClient.js';

// Mock fetch globally
const mockFetch = vi.fn();
global.fetch = mockFetch;

describe('OllamaNativeClient', () => {
  let client: OllamaNativeClient;

  beforeEach(() => {
    client = new OllamaNativeClient();
    mockFetch.mockReset();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  // ==========================================================================
  // Constructor and Configuration
  // ==========================================================================

  describe('constructor', () => {
    it('should use default values when no options provided', () => {
      expect(client.getBaseUrl()).toBe(DEFAULT_OLLAMA_NATIVE_URL);
    });

    it('should accept custom base URL', () => {
      const customClient = new OllamaNativeClient({
        baseUrl: 'http://custom-host:11434',
      });
      expect(customClient.getBaseUrl()).toBe('http://custom-host:11434');
    });

    it('should accept custom timeout', () => {
      const customClient = new OllamaNativeClient({
        timeout: 60000,
      });
      // Timeout is used internally, verified through request behavior
      expect(customClient).toBeDefined();
    });
  });

  describe('createOllamaNativeClient factory', () => {
    it('should create client with default options', () => {
      const factoryClient = createOllamaNativeClient();
      expect(factoryClient.getBaseUrl()).toBe(DEFAULT_OLLAMA_NATIVE_URL);
    });

    it('should create client with custom options', () => {
      const factoryClient = createOllamaNativeClient({
        baseUrl: 'http://remote-ollama:11434',
      });
      expect(factoryClient.getBaseUrl()).toBe('http://remote-ollama:11434');
    });
  });

  // ==========================================================================
  // Model Management API
  // ==========================================================================

  describe('listModels', () => {
    it('should call GET /api/tags', async () => {
      const mockResponse = {
        models: [
          {
            name: 'llama3.2:latest',
            modified_at: '2024-01-15T10:30:00Z',
            size: 4661224676,
            digest: 'abc123',
            details: {
              format: 'gguf',
              family: 'llama',
              parameter_size: '3B',
              quantization_level: 'Q4_0',
            },
          },
          {
            name: 'qwen2.5-coder:latest',
            modified_at: '2024-01-14T08:20:00Z',
            size: 5200000000,
            digest: 'def456',
            details: {
              format: 'gguf',
              family: 'qwen2',
              parameter_size: '7B',
              quantization_level: 'Q4_K_M',
            },
          },
        ],
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const result = await client.listModels();

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/tags`,
        expect.objectContaining({
          method: 'GET',
        }),
      );
      expect(result.models).toHaveLength(2);
      expect(result.models[0].name).toBe('llama3.2:latest');
      expect(result.models[1].name).toBe('qwen2.5-coder:latest');
    });

    it('should return empty array when no models', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ models: [] }),
      });

      const result = await client.listModels();
      expect(result.models).toHaveLength(0);
    });
  });

  describe('showModel', () => {
    it('should call POST /api/show with model name', async () => {
      const mockResponse = {
        modelfile: '# Modelfile generated by Ollama',
        parameters: 'temperature 0.7\nnum_ctx 4096',
        template: '{{ .System }}\n{{ .Prompt }}',
        details: {
          format: 'gguf',
          family: 'llama',
          parameter_size: '3B',
          quantization_level: 'Q4_0',
        },
        license: 'MIT',
        system: 'You are a helpful assistant.',
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const result = await client.showModel('llama3.2');

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/show`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({ model: 'llama3.2' }),
        }),
      );
      expect(result.modelfile).toContain('Modelfile');
      expect(result.parameters).toContain('temperature');
    });

    it('should accept full show request object', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          modelfile: '',
          parameters: '',
          template: '',
          details: { format: 'gguf', family: 'llama', parameter_size: '3B', quantization_level: 'Q4_0' },
        }),
      });

      await client.showModel({
        model: 'llava',
        system: 'Custom system prompt',
      });

      expect(mockFetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          body: JSON.stringify({
            model: 'llava',
            system: 'Custom system prompt',
          }),
        }),
      );
    });
  });

  describe('copyModel', () => {
    it('should call POST /api/copy', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({}),
      });

      await client.copyModel('llama3.2', 'llama3-backup');

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/copy`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({
            source: 'llama3.2',
            destination: 'llama3-backup',
          }),
        }),
      );
    });
  });

  describe('deleteModel', () => {
    it('should call DELETE /api/delete', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({}),
      });

      await client.deleteModel('llama3:13b');

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/delete`,
        expect.objectContaining({
          method: 'DELETE',
          body: JSON.stringify({ model: 'llama3:13b' }),
        }),
      );
    });
  });

  describe('pullModel', () => {
    it('should call POST /api/pull with non-streaming', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ status: 'success' }),
      });

      await client.pullModel('llama3.2');

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/pull`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({ name: 'llama3.2', stream: false }),
        }),
      );
    });
  });

  describe('pushModel', () => {
    it('should call POST /api/push with non-streaming', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ status: 'success' }),
      });

      await client.pushModel('mattw/pygmalion:latest');

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/push`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({ name: 'mattw/pygmalion:latest', stream: false }),
        }),
      );
    });
  });

  // ==========================================================================
  // Generation API
  // ==========================================================================

  describe('generate', () => {
    it('should call POST /api/generate with non-streaming', async () => {
      const mockResponse = {
        model: 'llama3.2',
        created_at: '2024-01-15T10:30:00Z',
        response: 'The sky appears blue due to Rayleigh scattering...',
        done: true,
        total_duration: 2500000000,
        eval_count: 150,
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const result = await client.generate({
        model: 'llama3.2',
        prompt: 'Why is the sky blue?',
      });

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/generate`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({
            model: 'llama3.2',
            prompt: 'Why is the sky blue?',
            stream: false,
          }),
        }),
      );
      expect(result.response).toContain('Rayleigh scattering');
      expect(result.done).toBe(true);
    });

    it('should accept generate options', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          model: 'llama3.2',
          created_at: '2024-01-15T10:30:00Z',
          response: 'Response',
          done: true,
        }),
      });

      await client.generate({
        model: 'llama3.2',
        prompt: 'Test',
        options: {
          temperature: 0.5,
          top_p: 0.9,
          num_ctx: 8192,
        },
      });

      const callBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(callBody.options.temperature).toBe(0.5);
      expect(callBody.options.top_p).toBe(0.9);
      expect(callBody.options.num_ctx).toBe(8192);
    });

    it('should support JSON format', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          model: 'llama3.2',
          created_at: '2024-01-15T10:30:00Z',
          response: '{"answer": "test"}',
          done: true,
        }),
      });

      await client.generate({
        model: 'llama3.2',
        prompt: 'Return JSON',
        format: 'json',
      });

      const callBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(callBody.format).toBe('json');
    });
  });

  describe('chat', () => {
    it('should call POST /api/chat with messages', async () => {
      const mockResponse = {
        model: 'llama3.2',
        created_at: '2024-01-15T10:30:00Z',
        message: {
          role: 'assistant',
          content: 'Hello! How can I help you today?',
        },
        done: true,
        total_duration: 1500000000,
        eval_count: 25,
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const result = await client.chat({
        model: 'llama3.2',
        messages: [
          { role: 'user', content: 'Hello!' },
        ],
      });

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/chat`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({
            model: 'llama3.2',
            messages: [{ role: 'user', content: 'Hello!' }],
            stream: false,
          }),
        }),
      );
      expect(result.message.content).toBe('Hello! How can I help you today?');
    });

    it('should support multi-turn conversation', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          model: 'llama3.2',
          created_at: '2024-01-15T10:30:00Z',
          message: { role: 'assistant', content: 'Response' },
          done: true,
        }),
      });

      await client.chat({
        model: 'llama3.2',
        messages: [
          { role: 'system', content: 'You are helpful.' },
          { role: 'user', content: 'Hello' },
          { role: 'assistant', content: 'Hi!' },
          { role: 'user', content: 'How are you?' },
        ],
      });

      const callBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(callBody.messages).toHaveLength(4);
    });

    it('should support tool calls', async () => {
      const mockResponse = {
        model: 'llama3.2',
        created_at: '2024-01-15T10:30:00Z',
        message: {
          role: 'assistant',
          content: '',
          tool_calls: [
            {
              function: {
                name: 'get_weather',
                arguments: { location: 'San Francisco' },
              },
            },
          ],
        },
        done: true,
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const tools = [
        {
          type: 'function' as const,
          function: {
            name: 'get_weather',
            description: 'Get weather for a location',
            parameters: {
              type: 'object',
              properties: {
                location: { type: 'string' },
              },
            },
          },
        },
      ];

      const result = await client.chat({
        model: 'llama3.2',
        messages: [{ role: 'user', content: 'What is the weather in SF?' }],
        tools,
      });

      expect(result.message.tool_calls).toBeDefined();
      expect(result.message.tool_calls![0].function.name).toBe('get_weather');
    });
  });

  // ==========================================================================
  // Embeddings API
  // ==========================================================================

  describe('embed', () => {
    it('should call POST /api/embed with multiple inputs', async () => {
      const mockResponse = {
        model: 'all-minilm',
        embeddings: [
          [0.1, 0.2, 0.3, 0.4],
          [0.5, 0.6, 0.7, 0.8],
        ],
        total_duration: 500000000,
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const result = await client.embed({
        model: 'all-minilm',
        input: ['Why is the sky blue?', 'Why is the grass green?'],
      });

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/embed`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({
            model: 'all-minilm',
            input: ['Why is the sky blue?', 'Why is the grass green?'],
          }),
        }),
      );
      expect(result.embeddings).toHaveLength(2);
    });

    it('should accept single string input', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          model: 'all-minilm',
          embeddings: [[0.1, 0.2, 0.3]],
        }),
      });

      await client.embed({
        model: 'all-minilm',
        input: 'Single text input',
      });

      const callBody = JSON.parse(mockFetch.mock.calls[0][1].body);
      expect(callBody.input).toBe('Single text input');
    });
  });

  describe('embeddings (legacy)', () => {
    it('should call POST /api/embeddings', async () => {
      const mockResponse = {
        embedding: [0.1, 0.2, 0.3, 0.4, 0.5],
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const result = await client.embeddings({
        model: 'all-minilm',
        prompt: 'Here is an article about llamas...',
      });

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/embeddings`,
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({
            model: 'all-minilm',
            prompt: 'Here is an article about llamas...',
          }),
        }),
      );
      expect(result.embedding).toHaveLength(5);
    });
  });

  // ==========================================================================
  // Server API
  // ==========================================================================

  describe('getVersion', () => {
    it('should call GET /api/version', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ version: '0.1.27' }),
      });

      const result = await client.getVersion();

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/version`,
        expect.objectContaining({ method: 'GET' }),
      );
      expect(result.version).toBe('0.1.27');
    });
  });

  describe('listRunningModels', () => {
    it('should call GET /api/ps', async () => {
      const mockResponse = {
        models: [
          {
            name: 'llama3.2:latest',
            model: 'llama3.2:latest',
            size: 4661224676,
            digest: 'abc123',
            details: {
              format: 'gguf',
              family: 'llama',
              parameter_size: '3B',
              quantization_level: 'Q4_0',
            },
            expires_at: '2024-01-15T11:30:00Z',
            size_vram: 4661224676,
          },
        ],
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockResponse),
      });

      const result = await client.listRunningModels();

      expect(mockFetch).toHaveBeenCalledWith(
        `${DEFAULT_OLLAMA_NATIVE_URL}/api/ps`,
        expect.objectContaining({ method: 'GET' }),
      );
      expect(result.models).toHaveLength(1);
      expect(result.models[0].name).toBe('llama3.2:latest');
    });

    it('should return empty array when no models running', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ models: [] }),
      });

      const result = await client.listRunningModels();
      expect(result.models).toHaveLength(0);
    });
  });

  // ==========================================================================
  // Utility Methods
  // ==========================================================================

  describe('isServerRunning', () => {
    it('should return true when server responds', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ version: '0.1.27' }),
      });

      const result = await client.isServerRunning();
      expect(result).toBe(true);
    });

    it('should return false when server fails', async () => {
      mockFetch.mockRejectedValueOnce(new Error('Connection refused'));

      const result = await client.isServerRunning();
      expect(result).toBe(false);
    });
  });

  describe('isModelAvailable', () => {
    it('should return true when model exists', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          models: [
            { name: 'llama3.2:latest', modified_at: '', size: 0, digest: '' },
          ],
        }),
      });

      const result = await client.isModelAvailable('llama3.2');
      expect(result).toBe(true);
    });

    it('should return false when model does not exist', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ models: [] }),
      });

      const result = await client.isModelAvailable('nonexistent');
      expect(result).toBe(false);
    });

    it('should match model with tag', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({
          models: [
            { name: 'llama3.2:13b', modified_at: '', size: 0, digest: '' },
          ],
        }),
      });

      const result = await client.isModelAvailable('llama3.2');
      expect(result).toBe(true);
    });
  });

  // ==========================================================================
  // Error Handling
  // ==========================================================================

  describe('error handling', () => {
    it('should throw error on HTTP error', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 404,
        statusText: 'Not Found',
        text: () => Promise.resolve('{"error": "model not found"}'),
      });

      await expect(client.showModel('nonexistent')).rejects.toThrow(
        'model not found',
      );
    });

    it('should include status code when no JSON error', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 500,
        statusText: 'Internal Server Error',
        text: () => Promise.resolve('Internal error'),
      });

      await expect(client.generate({ model: 'test', prompt: 'test' })).rejects.toThrow(
        'Ollama API error: 500',
      );
    });

    it('should handle connection errors', async () => {
      mockFetch.mockRejectedValueOnce(new Error('fetch failed'));

      await expect(client.getVersion()).rejects.toThrow('fetch failed');
    });
  });
});
